# set to true in frontmatter if required
math: false

releases:
  exe:
    version: 1.18.0
    filename: Cryptomator-1.18.0-x64.exe
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.18.0/Cryptomator-1.18.0-x64.exe
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.18.0/Cryptomator-1.18.0-x64.exe.asc
    checksum: f5981c3ac18f12088ee17e61a2136d0701631a09bffa88a926b4c7d61584af4d
    requiredOS: Windows 10, Version 1803
  msi:
    version: 1.18.0
    filename: Cryptomator-1.18.0-x64.msi
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.18.0/Cryptomator-1.18.0-x64.msi
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.18.0/Cryptomator-1.18.0-x64.msi.asc
    checksum: 9f7d959427046114607083e2f05108a804fd6151fc39ad76520b6c1fb64f32a8
    requiredOS: Windows 10, Version 1803
  dmg:
    version: 1.18.0
    filename: Cryptomator-1.18.0.dmg
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.18.0/Cryptomator-1.18.0-x64.dmg
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.18.0/Cryptomator-1.18.0-x64.dmg.asc
    checksum: b8b28bf17ad03864dd0ce3f5894ae1384f3b10d6423f580fabda4ad11ab1b79a
    requiredOS: macOS 11
  dmg-arm64:
    version: 1.18.0
    filename: Cryptomator-1.18.0-arm64.dmg
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.18.0/Cryptomator-1.18.0-arm64.dmg
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.18.0/Cryptomator-1.18.0-arm64.dmg.asc
    checksum: 1416c189da2890a234452a23d6d566e7eba4d79babf18423edc656344c676d13
    requiredOS: macOS 11
  appimage:
    version: 1.18.0
    filename: cryptomator-1.18.0-x86_64.AppImage
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.18.0/cryptomator-1.18.0-x86_64.AppImage
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.18.0/cryptomator-1.18.0-x86_64.AppImage.asc
    checksum: a75365252bf511875a1beccbd684b82d94166841dc6437f05c2ebb261350e780
    requiredOS: ""
  appimage-aarch64:
    version: 1.18.0
    filename: cryptomator-1.18.0-aarch64.AppImage
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.18.0/cryptomator-1.18.0-aarch64.AppImage
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.18.0/cryptomator-1.18.0-aarch64.AppImage.asc
    checksum: 12e66beaa6cf27a8931e384808cb316859db5322530de6690ea7f6ee6485b482
    requiredOS: ""
  android:
    version: 1.11.1
    filename: Cryptomator-1.11.1.apk
    downloadUrl: https://static.cryptomator.org/android/1.11.1/Cryptomator-1.11.1.apk
    checksum: cd779e929277920e65b282f166e9c693fe560927215428796e100bcc7427132a
    requiredOS: Android 8.0
