# API
apiBaseUrl: http://localhost:3300
legacyStoreUrl: http://localhost:8787/api

# UMAMI
umamiWebsiteId: 57a36f3a-bd97-4d8a-9563-0e8d39ddb20c

# PADDLE
paddleEnableSandbox: true
paddleToken: test_693d7082cf217f0c0d3cc21f888
paddleDesktopPriceIds: 
  - pri_01jb24dee06jaxrsz6xhfakkvy
  - pri_01jb24dvt2cj55r7p8agebef65
  - pri_01jb24e3z1zkzsq5yrhm5252bd
paddleAndroidPriceId: pri_01jb24ewyc6fbhnzt26jdj9qp1
paddleVendorId: 1385
paddleHubSelfHostedSubscriptionPlanId: 23141
paddleHubManagedSubscriptionPlanId: 42235
paddlePricesUrl: https://sandbox-checkout.paddle.com/api/2.0/prices
paddleDiscountId: dsc_01kba2drz2yg4v6h3d5f2687tw
paddleDiscountCode: WINTER2025

# STRIPE
stripePk: pk_test_51RCM24IBZmkR4F9UiLBiSmsAnJvWqmHcDLxXR8ABKK1MNsZk3zCk2VJW7ZfaBlD81zpQxCX243sS3LEp9dABwiG800kJnGykDF
